services:
  wishlist:
    image: guilhermesalviano/wishlist:latest
    container_name: wishlist
    restart: unless-stopped
    env_file:
      - .env.wishlist
    network_mode: bridge
    deploy:
      resources:
        limits:
          memory: 512M
